spring:
  application:
    name: numbers

security:
  basic:
    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.cloud: DEBUG
    io.pivotal.springcloud: DEBUG
server:
  port: 0